import {
  ShieldCheck,
  FolderKanban,
  FileSignature,
  User,
  Users,
  FileText,
  Settings,
  Info,
  Wrench,
  Phone,
  HelpCircle,
  Menu,
  Lock,
  ScrollText,
  FileBadge,
  Eye,
  Edit2,
  Trash2,
  Plus,
  GripVertical,
  Save,
  ChevronDown,
  ChevronRight,
  Home,
  Search,
  Bell,
  Mail,
  Calendar,
  Clock,
  Download,
  Upload,
  Copy,
  Check,
  X,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Filter,
  RefreshCw,
  ExternalLink,
  Link,
  Unlink,
  ImageIcon,
  Video,
  Music,
  Camera,
  Mic,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Package,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Folder,
  FolderOpen,
  File,
  FilePlus,
  FileX,
  Bookmark,
  BookmarkPlus,
  Star,
  Heart,
  Share2,
  MessageSquare,
  MessageCircle,
  Send,
  Paperclip,
  Tag,
  Hash,
  AtSign,
  Globe,
  MapPin,
  Navigation,
  Target,
  Award,
  Zap,
  Sun,
  Moon,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Power,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCheck,
} from 'lucide-react';

export const iconMap: Record<string, React.ReactNode> = {
  ShieldCheck: <ShieldCheck size={18} />,
  FolderKanban: <FolderKanban size={16} />,
  FileSignature: <FileSignature size={16} />,
  User: <User size={16} />,
  Users: <Users size={16} />,
  FileText: <FileText size={16} />,
  Settings: <Settings size={18} />,
  Info: <Info size={16} />,
  Wrench: <Wrench size={16} />,
  Phone: <Phone size={16} />,
  HelpCircle: <HelpCircle size={16} />,
  Menu: <Menu size={16} />,
  Lock: <Lock size={16} />,
  ScrollText: <ScrollText size={16} />,
  FileBadge: <FileBadge size={16} />,
  Eye: <Eye size={16} />,
  Edit2: <Edit2 size={16} />,
  Trash2: <Trash2 size={16} />,
  Plus: <Plus size={16} />,
  GripVertical: <GripVertical size={16} />,
  Save: <Save size={16} />,
  ChevronDown: <ChevronDown size={16} />,
  ChevronRight: <ChevronRight size={16} />,
  Home: <Home size={16} />,
  Search: <Search size={16} />,
  Bell: <Bell size={16} />,
  Mail: <Mail size={16} />,
  Calendar: <Calendar size={16} />,
  Clock: <Clock size={16} />,
  Download: <Download size={16} />,
  Upload: <Upload size={16} />,
  Copy: <Copy size={16} />,
  Check: <Check size={16} />,
  X: <X size={16} />,
  AlertCircle: <AlertCircle size={16} />,
  AlertTriangle: <AlertTriangle size={16} />,
  ArrowLeft: <ArrowLeft size={16} />,
  ArrowRight: <ArrowRight size={16} />,
  ArrowUp: <ArrowUp size={16} />,
  ArrowDown: <ArrowDown size={16} />,
  Filter: <Filter size={16} />,
  RefreshCw: <RefreshCw size={16} />,
  ExternalLink: <ExternalLink size={16} />,
  Link: <Link size={16} />,
  Unlink: <Unlink size={16} />,
  Image: <ImageIcon size={16} />,
  Video: <Video size={16} />,
  Music: <Music size={16} />,
  Camera: <Camera size={16} />,
  Mic: <Mic size={16} />,
  ShoppingCart: <ShoppingCart size={16} />,
  CreditCard: <CreditCard size={16} />,
  DollarSign: <DollarSign size={16} />,
  Package: <Package size={16} />,
  BarChart: <BarChart size={16} />,
  PieChart: <PieChart size={16} />,
  TrendingUp: <TrendingUp size={16} />,
  TrendingDown: <TrendingDown size={16} />,
  Activity: <Activity size={16} />,
  Database: <Database size={16} />,
  Server: <Server size={16} />,
  Cloud: <Cloud size={16} />,
  CloudUpload: <CloudUpload size={16} />,
  CloudDownload: <CloudDownload size={16} />,
  Folder: <Folder size={16} />,
  FolderOpen: <FolderOpen size={16} />,
  File: <File size={16} />,
  FilePlus: <FilePlus size={16} />,
  FileX: <FileX size={16} />,
  Bookmark: <Bookmark size={16} />,
  BookmarkPlus: <BookmarkPlus size={16} />,
  Star: <Star size={16} />,
  Heart: <Heart size={16} />,
  Share2: <Share2 size={16} />,
  MessageSquare: <MessageSquare size={16} />,
  MessageCircle: <MessageCircle size={16} />,
  Send: <Send size={16} />,
  Paperclip: <Paperclip size={16} />,
  Tag: <Tag size={16} />,
  Hash: <Hash size={16} />,
  AtSign: <AtSign size={16} />,
  Globe: <Globe size={16} />,
  MapPin: <MapPin size={16} />,
  Navigation: <Navigation size={16} />,
  Target: <Target size={16} />,
  Award: <Award size={16} />,
  Zap: <Zap size={16} />,
  Sun: <Sun size={16} />,
  Moon: <Moon size={16} />,
  Volume2: <Volume2 size={16} />,
  VolumeX: <VolumeX size={16} />,
  Play: <Play size={16} />,
  Pause: <Pause size={16} />,
  SkipBack: <SkipBack size={16} />,
  SkipForward: <SkipForward size={16} />,
  Power: <Power size={16} />,
  LogIn: <LogIn size={16} />,
  LogOut: <LogOut size={16} />,
  UserPlus: <UserPlus size={16} />,
  UserMinus: <UserMinus size={16} />,
  UserCheck: <UserCheck size={16} />,
};

export const iconOptions = Object.keys(iconMap);

