import mongoose, { Schema } from 'mongoose';

const roleSchema = new Schema(
  {
    name: { type: String },
    email: {
      type: String,
      match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Please enter a valid email'],
    },
    role: {
      user: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      website_setting: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      role_permission: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      access_management: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      course: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      review: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      lecture: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      batch: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      q_and_a: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      content_resource: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      assessment: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      payment: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      submissions: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      enrollment: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      marketing_lead: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      profile: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      message: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      media: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      follow_up: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      attendance: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      company_goal: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      support_ticket: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      post: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      reward: {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
      'employee_task ': {
        create: Boolean,
        read: Boolean,
        update: Boolean,
        delete: Boolean,
        dashboard_parsonal: Boolean,
        dashboard_admin: Boolean,
      },
    },
  },
  { timestamps: true },
);

export default mongoose.models.Role || mongoose.model('Role', roleSchema);
